// Alle Kategorien und ihre Karten-Pools.
//
// Jede Kategorie hat 40 Karten. Die meisten sind starke/beliebte
// Einträge, dazu kommen ein paar (meist 3-5) echte, aber im
// Vergleich schwächere oder unbeliebtere Einträge (weak: true) -
// keine erfundenen Spass-Sprüche, sondern Dinge, die es wirklich
// gibt (z. B. ein bekannter, aber zuletzt schwacher Spieler, oder
// ein Auto, das für seine hässliche Form bekannt ist). Pro Runde
// werden aus den 40 per Zufall 8 gezogen und versteigert (siehe
// engine.ts) - dadurch ist nie im Voraus klar, ob eine "weak"-Karte
// mit dabei ist.
//
// Bilder: standardmäßig Emojis statt echter Fotos/Logos - Fotos von
// echten Promis/Sportlern oder echte Marken-Logos fest einzubauen
// ist urheber-/markenrechtlich heikel, vor allem weil das Spiel
// öffentlich online läuft. Die Namen selbst (Text) zu verwenden ist
// unproblematisch - nur echte Bild-/Logo-Dateien würden ein Risiko
// sein. Wer trotzdem ein echtes Bild will, trägt bei einer Karte
// `image` ein (eine Bild-URL) - das überschreibt dann das Emoji.
// Schlägt das Laden fehl (Link kaputt, Seite offline), springt die
// Anzeige automatisch zurück aufs Emoji.

export type CategoryItem = {
  name: string;
  /** Bekannt, aber im Vergleich schwächer/unbeliebter - zählt beim
   *  Computer-Urteil am Ende weniger. */
  weak?: boolean;
  /** Überschreibt das Kategorie-Emoji für diese eine Karte. */
  emoji?: string;
  /** Optional: URL zu einem echten Bild, überschreibt das Emoji. */
  image?: string;
};

export type Category = {
  id: string;
  label: string;
  /** Fällt zurück, wenn eine Karte kein eigenes Emoji hat. */
  emoji: string;
  items: CategoryItem[];
};

export const CATEGORIES: Category[] = [
  {
    id: "fussballvereine",
    label: "Fußballvereine",
    emoji: "🏟️",
    items: [
      { name: "Real Madrid" },
      { name: "FC Barcelona" },
      { name: "Manchester City" },
      { name: "Liverpool" },
      { name: "Manchester United" },
      { name: "Bayern München" },
      { name: "Borussia Dortmund" },
      { name: "Arsenal" },
      { name: "Chelsea" },
      { name: "Paris Saint-Germain" },
      { name: "Inter Mailand" },
      { name: "AC Milan" },
      { name: "Juventus" },
      { name: "Atlético Madrid" },
      { name: "Tottenham Hotspur" },
      { name: "Bayer Leverkusen" },
      { name: "RB Leipzig" },
      { name: "Napoli" },
      { name: "AS Rom" },
      { name: "Benfica Lissabon" },
      { name: "FC Porto" },
      { name: "Ajax Amsterdam" },
      { name: "PSV Eindhoven" },
      { name: "Feyenoord" },
      { name: "Galatasaray" },
      { name: "Fenerbahçe" },
      { name: "Sporting Lissabon" },
      { name: "Sevilla" },
      { name: "Valencia", weak: true },
      { name: "Aston Villa" },
      { name: "Newcastle United" },
      { name: "West Ham United", weak: true },
      { name: "Eintracht Frankfurt" },
      { name: "Borussia Mönchengladbach" },
      { name: "VfB Stuttgart" },
      { name: "Schalke 04", weak: true },
      { name: "Celtic" },
      { name: "Rangers" },
      { name: "Nottingham Forest", weak: true },
      { name: "FC Köln", weak: true },
    ],
  },
  {
    id: "nba",
    label: "NBA-Spieler",
    emoji: "🏀",
    items: [
      { name: "Michael Jordan" },
      { name: "LeBron James" },
      { name: "Kobe Bryant" },
      { name: "Stephen Curry" },
      { name: "Shaquille O'Neal" },
      { name: "Magic Johnson" },
      { name: "Larry Bird" },
      { name: "Kareem Abdul-Jabbar" },
      { name: "Tim Duncan" },
      { name: "Kevin Durant" },
      { name: "Giannis Antetokounmpo" },
      { name: "Nikola Jokić" },
      { name: "Luka Dončić" },
      { name: "Allen Iverson" },
      { name: "Dwyane Wade" },
      { name: "Kevin Garnett" },
      { name: "Dirk Nowitzki" },
      { name: "Hakeem Olajuwon" },
      { name: "Wilt Chamberlain" },
      { name: "Bill Russell" },
      { name: "Kawhi Leonard" },
      { name: "James Harden" },
      { name: "Russell Westbrook", weak: true },
      { name: "Chris Paul" },
      { name: "Anthony Davis" },
      { name: "Jayson Tatum" },
      { name: "Anthony Edwards" },
      { name: "Devin Booker" },
      { name: "Damian Lillard" },
      { name: "Kyrie Irving" },
      { name: "Joel Embiid" },
      { name: "Ja Morant" },
      { name: "Tracy McGrady" },
      { name: "Vince Carter" },
      { name: "Carmelo Anthony" },
      { name: "Paul George" },
      { name: "Dwight Howard", weak: true },
      { name: "Klay Thompson" },
      { name: "DeMar DeRozan" },
      { name: "Ben Simmons", weak: true },
    ],
  },
  {
    id: "nfl",
    label: "NFL-Spieler",
    emoji: "🏈",
    items: [
      { name: "Tom Brady" },
      { name: "Patrick Mahomes" },
      { name: "Peyton Manning" },
      { name: "Aaron Rodgers" },
      { name: "Joe Montana" },
      { name: "Jerry Rice" },
      { name: "Randy Moss" },
      { name: "Barry Sanders" },
      { name: "Walter Payton" },
      { name: "Emmitt Smith" },
      { name: "Ray Lewis" },
      { name: "Lawrence Taylor" },
      { name: "Rob Gronkowski" },
      { name: "Travis Kelce" },
      { name: "Lamar Jackson" },
      { name: "Josh Allen" },
      { name: "Joe Burrow" },
      { name: "Justin Jefferson" },
      { name: "Tyreek Hill" },
      { name: "Derrick Henry" },
      { name: "Adrian Peterson" },
      { name: "Calvin Johnson" },
      { name: "Deion Sanders" },
      { name: "Terrell Owens" },
      { name: "Brett Favre" },
      { name: "Drew Brees" },
      { name: "Dan Marino" },
      { name: "John Elway" },
      { name: "Steve Young" },
      { name: "Cam Newton", weak: true },
      { name: "Saquon Barkley" },
      { name: "Christian McCaffrey" },
      { name: "Davante Adams" },
      { name: "Odell Beckham Jr.", weak: true },
      { name: "J.J. Watt" },
      { name: "Von Miller" },
      { name: "Micah Parsons" },
      { name: "CeeDee Lamb" },
      { name: "Dak Prescott" },
      { name: "Russell Wilson", weak: true },
    ],
  },
  {
    id: "f1",
    label: "Formel 1",
    emoji: "🏎️",
    items: [
      { name: "Michael Schumacher" },
      { name: "Lewis Hamilton" },
      { name: "Ayrton Senna" },
      { name: "Max Verstappen" },
      { name: "Fernando Alonso" },
      { name: "Sebastian Vettel" },
      { name: "Alain Prost" },
      { name: "Niki Lauda" },
      { name: "Juan Manuel Fangio" },
      { name: "Charles Leclerc" },
      { name: "Lando Norris" },
      { name: "Kimi Räikkönen" },
      { name: "Nigel Mansell" },
      { name: "Jackie Stewart" },
      { name: "Oscar Piastri" },
      { name: "Nico Rosberg" },
      { name: "Mika Häkkinen" },
      { name: "Damon Hill" },
      { name: "Jenson Button" },
      { name: "Daniel Ricciardo" },
      { name: "George Russell" },
      { name: "Carlos Sainz" },
      { name: "Sergio Pérez", weak: true },
      { name: "Valtteri Bottas" },
      { name: "Felipe Massa" },
      { name: "Rubens Barrichello" },
      { name: "Gilles Villeneuve" },
      { name: "Jacques Villeneuve" },
      { name: "Juan Pablo Montoya" },
      { name: "Pierre Gasly" },
      { name: "Esteban Ocon" },
      { name: "Yuki Tsunoda", weak: true },
      { name: "Alex Albon" },
      { name: "Lance Stroll", weak: true },
      { name: "Nico Hülkenberg", weak: true },
      { name: "Nelson Piquet" },
      { name: "James Hunt" },
      { name: "Emerson Fittipaldi" },
      { name: "Jack Brabham" },
      { name: "Jim Clark" },
    ],
  },
  {
    id: "autos",
    label: "Autos",
    emoji: "🚗",
    items: [
      { name: "Bugatti Chiron", emoji: "🏎️" },
      { name: "Bugatti Mistral", emoji: "🏎️" },
      { name: "Lamborghini Aventador", emoji: "🏎️" },
      { name: "Lamborghini Urus", emoji: "🚙" },
      { name: "Lamborghini Revuelto", emoji: "🏎️" },
      { name: "Ferrari SF90", emoji: "🏎️" },
      { name: "Ferrari 488", emoji: "🏎️" },
      { name: "Ferrari LaFerrari", emoji: "🏎️" },
      { name: "McLaren P1", emoji: "🏎️" },
      { name: "McLaren 720S", emoji: "🏎️" },
      { name: "Porsche 911 GT3 RS", emoji: "🏎️" },
      { name: "Porsche 918 Spyder", emoji: "🏎️" },
      { name: "Mercedes-AMG GT", emoji: "🏎️" },
      { name: "Mercedes G-Klasse", emoji: "🚙" },
      { name: "BMW M3", emoji: "🚗" },
      { name: "BMW M5", emoji: "🚗" },
      { name: "Audi R8", emoji: "🏎️" },
      { name: "Audi RS6", emoji: "🚗" },
      { name: "Nissan GT-R", emoji: "🏎️" },
      { name: "Toyota Supra", emoji: "🏎️" },
      { name: "Ford Mustang", emoji: "🐎" },
      { name: "Chevrolet Corvette", emoji: "🏎️" },
      { name: "Dodge Challenger", emoji: "🚗" },
      { name: "Tesla Model S", emoji: "🔋" },
      { name: "Tesla Cybertruck", emoji: "🔋" },
      { name: "Jeep Wrangler", emoji: "🚙" },
      { name: "Range Rover", emoji: "🚙" },
      { name: "Land Rover Defender", emoji: "🚙" },
      { name: "Volkswagen Golf GTI", emoji: "🚗" },
      { name: "Volkswagen Golf 4", emoji: "🚗" },
      { name: "Mazda MX-5", emoji: "🚗" },
      { name: "Subaru Impreza WRX STI", emoji: "🚗" },
      { name: "Honda Civic Type R", emoji: "🚗" },
      { name: "Fiat 500", emoji: "🚗" },
      { name: "Smart Fortwo", weak: true, emoji: "🚗" },
      { name: "Toyota Prius", emoji: "🚗" },
      { name: "Nissan Juke", weak: true, emoji: "🚗" },
      { name: "Pontiac Aztek", weak: true, emoji: "🚙" },
      { name: "Fiat Multipla", weak: true, emoji: "🚐" },
      { name: "PT Cruiser", weak: true, emoji: "🚗" },
    ],
  },
  {
    id: "kindheitsserien",
    label: "Serien aus der Kindheit",
    emoji: "📺",
    items: [
      { name: "SpongeBob Schwammkopf" },
      { name: "Die Simpsons" },
      { name: "Phineas und Ferb" },
      { name: "iCarly" },
      { name: "Victorious" },
      { name: "Hannah Montana" },
      { name: "Drake & Josh" },
      { name: "Zoey 101" },
      { name: "Wizards of Waverly Place" },
      { name: "Suite Life of Zack & Cody" },
      { name: "Kim Possible" },
      { name: "American Dragon", weak: true },
      { name: "Danny Phantom" },
      { name: "Avatar – Der Herr der Elemente" },
      { name: "Pokémon" },
      { name: "Digimon" },
      { name: "Yu-Gi-Oh!" },
      { name: "Ben 10" },
      { name: "Teen Titans" },
      { name: "Totally Spies!" },
      { name: "Winx Club" },
      { name: "Detektiv Conan" },
      { name: "One Piece" },
      { name: "Naruto" },
      { name: "Malcolm mittendrin" },
      { name: "Ned's ultimativer Schulwahnsinn" },
      { name: "Big Time Rush" },
      { name: "Pair of Kings", weak: true },
      { name: "Jessie" },
      { name: "Good Luck Charlie" },
      { name: "Austin & Ally" },
      { name: "Kick Buttowski", weak: true },
      { name: "Gravity Falls" },
      { name: "Adventure Time" },
      { name: "Regular Show" },
      { name: "The Amazing World of Gumball" },
      { name: "Johnny Test", weak: true },
      { name: "Cosmo & Wanda" },
      { name: "Die wilden Siebziger" },
      { name: "Codename: Kids Next Door" },
    ],
  },
  {
    id: "filme2000er",
    label: "Filme aus den 2000ern",
    emoji: "🎬",
    items: [
      { name: "The Dark Knight" },
      { name: "Harry Potter und der Stein der Weisen" },
      { name: "Harry Potter und der Feuerkelch" },
      { name: "Der Herr der Ringe: Die Gefährten" },
      { name: "Der Herr der Ringe: Die zwei Türme" },
      { name: "Der Herr der Ringe: Die Rückkehr des Königs" },
      { name: "Fluch der Karibik" },
      { name: "Gladiator" },
      { name: "Inception" },
      { name: "Avatar" },
      { name: "Iron Man" },
      { name: "Spider-Man" },
      { name: "Spider-Man 2" },
      { name: "Transformers" },
      { name: "Shrek" },
      { name: "Shrek 2" },
      { name: "Ratatouille" },
      { name: "WALL-E" },
      { name: "Findet Nemo" },
      { name: "Die Unglaublichen" },
      { name: "Cars" },
      { name: "Kung Fu Panda" },
      { name: "Hangover" },
      { name: "Superbad" },
      { name: "Mean Girls" },
      { name: "Twilight" },
      { name: "Casino Royale" },
      { name: "No Country for Old Men" },
      { name: "Inglourious Basterds" },
      { name: "The Departed" },
      { name: "Gran Torino" },
      { name: "300" },
      { name: "I Am Legend" },
      { name: "The Pursuit of Happyness" },
      { name: "Step Up" },
      { name: "High School Musical" },
      { name: "Alvin und die Chipmunks", weak: true },
      { name: "Paul Blart: Mall Cop", weak: true },
      { name: "Eragon", weak: true },
      { name: "Catwoman", weak: true },
    ],
  },
  {
    id: "songs2010er",
    label: "Songs aus den 2010ern",
    emoji: "🎵",
    items: [
      { name: "Happy – Pharrell Williams" },
      { name: "Shape of You – Ed Sheeran" },
      { name: "Uptown Funk – Mark Ronson ft. Bruno Mars" },
      { name: "Someone Like You – Adele" },
      { name: "Rolling in the Deep – Adele" },
      { name: "Despacito – Luis Fonsi" },
      { name: "Old Town Road – Lil Nas X", weak: true },
      { name: "Sorry – Justin Bieber" },
      { name: "Love Yourself – Justin Bieber" },
      { name: "Thinking Out Loud – Ed Sheeran" },
      { name: "Perfect – Ed Sheeran" },
      { name: "Rockstar – Post Malone" },
      { name: "Sunflower – Post Malone & Swae Lee" },
      { name: "God's Plan – Drake" },
      { name: "Hotline Bling – Drake" },
      { name: "HUMBLE. – Kendrick Lamar" },
      { name: "Sicko Mode – Travis Scott" },
      { name: "Goosebumps – Travis Scott" },
      { name: "Bad Guy – Billie Eilish" },
      { name: "Lovely – Billie Eilish" },
      { name: "Havana – Camila Cabello" },
      { name: "Señorita – Shawn Mendes & Camila Cabello" },
      { name: "Shallow – Lady Gaga & Bradley Cooper" },
      { name: "Cheap Thrills – Sia" },
      { name: "Chandelier – Sia" },
      { name: "Radioactive – Imagine Dragons" },
      { name: "Believer – Imagine Dragons" },
      { name: "Counting Stars – OneRepublic" },
      { name: "Let Her Go – Passenger" },
      { name: "Wake Me Up – Avicii" },
      { name: "Levels – Avicii" },
      { name: "We Found Love – Rihanna" },
      { name: "Diamonds – Rihanna" },
      { name: "Starships – Nicki Minaj", weak: true },
      { name: "The Hills – The Weeknd" },
      { name: "Can't Feel My Face – The Weeknd" },
      { name: "Gangnam Style – PSY", weak: true },
      { name: "Somebody That I Used to Know – Gotye" },
      { name: "Royals – Lorde" },
      { name: "What Makes You Beautiful – One Direction", weak: true },
    ],
  },
  {
    id: "videospiele",
    label: "Videospiele",
    emoji: "🎮",
    items: [
      { name: "Minecraft" },
      { name: "GTA V" },
      { name: "GTA San Andreas" },
      { name: "Red Dead Redemption 2" },
      { name: "Fortnite" },
      { name: "Call of Duty: Black Ops II" },
      { name: "Call of Duty: Modern Warfare 2" },
      { name: "FIFA" },
      { name: "Mario Kart Wii" },
      { name: "Super Mario Bros." },
      { name: "Super Mario Odyssey" },
      { name: "The Legend of Zelda: Breath of the Wild" },
      { name: "The Legend of Zelda: Ocarina of Time" },
      { name: "Pokémon Rot/Blau" },
      { name: "Pokémon Diamant/Perl" },
      { name: "Pokémon Schwarz/Weiß" },
      { name: "Wii Sports" },
      { name: "Wii Fit", weak: true },
      { name: "Rocket League" },
      { name: "Roblox" },
      { name: "Terraria" },
      { name: "Among Us" },
      { name: "FIFA Street", weak: true },
      { name: "Need for Speed Most Wanted" },
      { name: "Need for Speed Underground 2" },
      { name: "Gran Turismo" },
      { name: "Forza Horizon 5" },
      { name: "Skyrim" },
      { name: "Fallout 4" },
      { name: "The Witcher 3" },
      { name: "Elden Ring" },
      { name: "Dark Souls" },
      { name: "God of War" },
      { name: "Spider-Man" },
      { name: "The Last of Us" },
      { name: "Uncharted 4" },
      { name: "Super Smash Bros. Ultimate" },
      { name: "Animal Crossing: New Horizons" },
      { name: "Fall Guys" },
      { name: "Goat Simulator", weak: true },
    ],
  },
  {
    id: "logos",
    label: "Logos",
    emoji: "🏷️",
    items: [
      { name: "Nike" },
      { name: "Adidas" },
      { name: "Apple" },
      { name: "McDonald's" },
      { name: "Coca-Cola" },
      { name: "Pepsi", weak: true },
      { name: "Mercedes-Benz" },
      { name: "BMW" },
      { name: "Ferrari" },
      { name: "Lamborghini" },
      { name: "Porsche" },
      { name: "Audi" },
      { name: "Toyota" },
      { name: "Volkswagen" },
      { name: "Ford" },
      { name: "Chevrolet" },
      { name: "PlayStation" },
      { name: "Xbox" },
      { name: "Nintendo" },
      { name: "YouTube" },
      { name: "Instagram" },
      { name: "TikTok" },
      { name: "Snapchat", weak: true },
      { name: "Netflix" },
      { name: "Disney" },
      { name: "Warner Bros." },
      { name: "Amazon" },
      { name: "Google" },
      { name: "Microsoft" },
      { name: "Meta" },
      { name: "Spotify" },
      { name: "Starbucks" },
      { name: "KFC" },
      { name: "Burger King" },
      { name: "Lego" },
      { name: "Gucci" },
      { name: "Louis Vuitton" },
      { name: "Rolex" },
      { name: "Shell", weak: true },
      { name: "Red Bull" },
    ],
  },
  {
    id: "marken",
    label: "Marken",
    emoji: "👑",
    items: [
      { name: "IKEA" },
      { name: "Zara" },
      { name: "H&M" },
      { name: "Levi's" },
      { name: "Ray-Ban" },
      { name: "Converse" },
      { name: "Vans" },
      { name: "New Balance" },
      { name: "Jordan (Brand)" },
      { name: "The North Face" },
      { name: "Patagonia" },
      { name: "Crocs", weak: true },
      { name: "Samsung" },
      { name: "Sony" },
      { name: "Louis Vuitton" },
      { name: "Rolex" },
      { name: "Gucci" },
      { name: "Prada" },
      { name: "Chanel" },
      { name: "Balenciaga" },
      { name: "Supreme" },
      { name: "Off-White" },
      { name: "Hugo Boss" },
      { name: "Calvin Klein" },
      { name: "Tommy Hilfiger" },
      { name: "Ralph Lauren" },
      { name: "Under Armour" },
      { name: "Puma" },
      { name: "Reebok" },
      { name: "Diesel", weak: true },
      { name: "Guess", weak: true },
      { name: "Michael Kors" },
      { name: "Versace" },
      { name: "Armani" },
      { name: "Dior" },
      { name: "Hermès" },
      { name: "Cartier" },
      { name: "Tiffany & Co." },
      { name: "Swarovski" },
      { name: "Victoria's Secret", weak: true },
    ],
  },
  {
    id: "zimmer",
    label: "Baue dein Zimmer",
    emoji: "🛏️",
    items: [
      { name: "King-Size-Bett", emoji: "🛏️" },
      { name: "Normales Doppelbett", emoji: "🛏️" },
      { name: "Einzelbett", emoji: "🛏️" },
      { name: "Wasserbett", emoji: "🌊" },
      { name: "Riesiger Fernseher", emoji: "📺" },
      { name: "Kleiner Fernseher", emoji: "📺" },
      { name: "Gaming-PC", emoji: "🖥️" },
      { name: "PlayStation 5", emoji: "🎮" },
      { name: "Xbox", emoji: "🎮" },
      { name: "Mini-Kühlschrank", emoji: "🧊" },
      { name: "Begehbarer Kleiderschrank", emoji: "👔" },
      { name: "Whirlpool", emoji: "🛁" },
      { name: "Riesiger Spiegel", emoji: "🪞" },
      { name: "Schminktisch", emoji: "💄" },
      { name: "Laufband", emoji: "🏃" },
      { name: "Hantelbank", emoji: "🏋️" },
      { name: "Massagesessel", emoji: "💺" },
      { name: "Aquarium", emoji: "🐠" },
      { name: "Balkon", emoji: "🏞️" },
      { name: "Dachfenster", emoji: "🌤️" },
      { name: "Kamin", emoji: "🔥" },
      { name: "Klimaanlage", emoji: "❄️" },
      { name: "Riesiges Sofa", emoji: "🛋️" },
      { name: "Sitzsack", emoji: "🛋️" },
      { name: "Schreibtisch", emoji: "🖊️" },
      { name: "Heimkino-Leinwand", emoji: "🎬" },
      { name: "Soundsystem", emoji: "🔊" },
      { name: "Bücherregal", emoji: "📚" },
      { name: "Begehbare Dusche im Zimmer", emoji: "🚿" },
      { name: "Eigene Minibar", emoji: "🍹" },
      { name: "Racing-Simulator-Ecke", emoji: "🏎️" },
      { name: "Plattenspieler", emoji: "🎵" },
      { name: "Triple-Monitor-Setup", emoji: "🖥️" },
      { name: "Sauna", emoji: "♨️" },
      { name: "Begehbarer Schuhschrank", emoji: "👟" },
      { name: "Luftmatratze", weak: true, emoji: "🫧" },
      { name: "Quietschende alte Feder-Matratze", weak: true, emoji: "🛏️" },
      { name: "Kaputter Klappstuhl vom Sperrmüll", weak: true, emoji: "🪑" },
      { name: "Zugiges Einfachglas-Fenster", weak: true, emoji: "🪟" },
      { name: "Neonröhre statt Lampe", weak: true, emoji: "💡" },
    ],
  },
];

export function categoryById(id: string): Category | undefined {
  return CATEGORIES.find((category) => category.id === id);
}

/** Das Emoji einer Karte: eigenes Emoji, sonst das der Kategorie. */
export function itemEmoji(categoryId: string, item: CategoryItem): string {
  return item.emoji ?? categoryById(categoryId)?.emoji ?? "🃏";
}
