// Alle Kategorien und ihre Karten-Pools.
//
// Jede Kategorie hat 50 Karten: 40 "richtig gute/starke" Karten und
// 10 Karten, die man zwar auf jeden Fall kennt, aber eher nicht wegen
// überragender Leistung (weak: true). Pro Runde werden aus den 50
// per Zufall 8 gezogen und versteigert (siehe engine.ts) - dadurch
// ist nie im Voraus klar, ob eine "weak"-Karte mit dabei ist.
//
// Bilder: standardmäßig Emojis statt echter Fotos - Fotos von
// echten Promis/Sportlern oder Bilder von urheberrechtlich
// geschützten Comicfiguren fest einzubauen ist rechtlich heikel,
// vor allem falls das Spiel mal veröffentlicht wird. Wer trotzdem
// ein echtes Bild will, trägt bei einer Karte `image` ein (eine
// Bild-URL) - das überschreibt dann das Emoji. Schlägt das Laden
// fehl (Link kaputt, Seite offline), springt die Anzeige automatisch
// zurück aufs Emoji.

export type CategoryItem = {
  name: string;
  /** Bekannt, aber eher nicht wegen Top-Leistung - zählt beim
   *  Computer-Urteil am Ende weniger. */
  weak?: boolean;
  /** Überschreibt das Kategorie-Emoji für diese eine Karte. */
  emoji?: string;
  /** Optional: URL zu einem echten Bild, überschreibt das Emoji. */
  image?: string;
};

export type Category = {
  id: string;
  label: string;
  /** Fällt zurück, wenn eine Karte kein eigenes Emoji hat. */
  emoji: string;
  items: CategoryItem[];
};

export const CATEGORIES: Category[] = [
  {
    id: "fussball",
    label: "Fußball-Stars",
    emoji: "⚽",
    items: [
      { name: "Lionel Messi" },
      { name: "Cristiano Ronaldo" },
      { name: "Kylian Mbappé" },
      { name: "Erling Haaland" },
      { name: "Neymar" },
      { name: "Mohamed Salah" },
      { name: "Kevin De Bruyne" },
      { name: "Luka Modrić" },
      { name: "Robert Lewandowski" },
      { name: "Harry Kane" },
      { name: "Jude Bellingham" },
      { name: "Vinícius Júnior" },
      { name: "Antoine Griezmann" },
      { name: "Toni Kroos" },
      { name: "Joshua Kimmich" },
      { name: "Jamal Musiala" },
      { name: "Pedri" },
      { name: "Rodri" },
      { name: "Zinédine Zidane" },
      { name: "Ronaldinho" },
      { name: "Pelé" },
      { name: "Diego Maradona" },
      { name: "Thierry Henry" },
      { name: "David Beckham" },
      { name: "Andrés Iniesta" },
      { name: "Xavi Hernández" },
      { name: "Sergio Ramos" },
      { name: "Manuel Neuer" },
      { name: "Karim Benzema" },
      { name: "Bukayo Saka" },
      { name: "Phil Foden" },
      { name: "Florian Wirtz" },
      { name: "Declan Rice" },
      { name: "Marco Reus" },
      { name: "Thomas Müller" },
      { name: "Sadio Mané" },
      { name: "Virgil van Dijk" },
      { name: "Rúben Dias" },
      { name: "Alphonso Davies" },
      { name: "Federico Valverde" },
      { name: "Mario Balotelli", weak: true },
      { name: "Nicklas Bendtner", weak: true },
      { name: "Adebayo Akinfenwa", weak: true },
      { name: "Djibril Cissé", weak: true },
      { name: "Emile Heskey", weak: true },
      { name: "David Odonkor", weak: true },
      { name: "Timo Werner", weak: true },
      { name: "Kevin-Prince Boateng", weak: true },
      { name: "Fernando Torres", weak: true },
      { name: "Anthony Martial", weak: true },
    ],
  },
  {
    id: "basketball",
    label: "Basketball (NBA)",
    emoji: "🏀",
    items: [
      { name: "LeBron James" },
      { name: "Stephen Curry" },
      { name: "Kevin Durant" },
      { name: "Giannis Antetokounmpo" },
      { name: "Luka Dončić" },
      { name: "Nikola Jokić" },
      { name: "Kobe Bryant" },
      { name: "Michael Jordan" },
      { name: "Shaquille O'Neal" },
      { name: "Tim Duncan" },
      { name: "Kawhi Leonard" },
      { name: "Joel Embiid" },
      { name: "Jayson Tatum" },
      { name: "Damian Lillard" },
      { name: "James Harden" },
      { name: "Anthony Davis" },
      { name: "Kyrie Irving" },
      { name: "Devin Booker" },
      { name: "Ja Morant" },
      { name: "Victor Wembanyama" },
      { name: "Magic Johnson" },
      { name: "Larry Bird" },
      { name: "Kareem Abdul-Jabbar" },
      { name: "Wilt Chamberlain" },
      { name: "Hakeem Olajuwon" },
      { name: "Allen Iverson" },
      { name: "Dirk Nowitzki" },
      { name: "Dwyane Wade" },
      { name: "Chris Paul" },
      { name: "Russell Westbrook" },
      { name: "Paul George" },
      { name: "Jimmy Butler" },
      { name: "Karl-Anthony Towns" },
      { name: "Shai Gilgeous-Alexander" },
      { name: "Anthony Edwards" },
      { name: "Donovan Mitchell" },
      { name: "Zion Williamson" },
      { name: "Klay Thompson" },
      { name: "Draymond Green" },
      { name: "Carmelo Anthony" },
      { name: "Jeremy Lin", weak: true },
      { name: "Nick Young", weak: true },
      { name: "JaVale McGee", weak: true },
      { name: "Michael Beasley", weak: true },
      { name: "Kwame Brown", weak: true },
      { name: "Darko Miličić", weak: true },
      { name: "Greg Oden", weak: true },
      { name: "Metta World Peace", weak: true },
      { name: "Adam Morrison", weak: true },
      { name: "Anthony Bennett", weak: true },
    ],
  },
  {
    id: "superhelden",
    label: "Superhelden",
    emoji: "🦸",
    items: [
      { name: "Spider-Man" },
      { name: "Iron Man" },
      { name: "Batman" },
      { name: "Superman" },
      { name: "Wonder Woman" },
      { name: "Thor" },
      { name: "Hulk" },
      { name: "Captain America" },
      { name: "Black Panther" },
      { name: "The Flash" },
      { name: "Wolverine" },
      { name: "Deadpool" },
      { name: "Doctor Strange" },
      { name: "Aquaman" },
      { name: "Black Widow" },
      { name: "Green Lantern" },
      { name: "Scarlet Witch" },
      { name: "Shazam" },
      { name: "Captain Marvel" },
      { name: "Daredevil" },
      { name: "Green Arrow" },
      { name: "Cyborg" },
      { name: "Nightwing" },
      { name: "Storm" },
      { name: "Professor X" },
      { name: "Magneto" },
      { name: "Star-Lord" },
      { name: "Rocket Raccoon" },
      { name: "Groot" },
      { name: "Vision" },
      { name: "Ant-Man" },
      { name: "Hawkeye" },
      { name: "Nick Fury" },
      { name: "Catwoman" },
      { name: "Harley Quinn" },
      { name: "Joker" },
      { name: "Loki" },
      { name: "Venom" },
      { name: "Silver Surfer" },
      { name: "Batgirl" },
      { name: "Matter-Eater Lad (isst wortwörtlich alles)", weak: true, emoji: "🍽️" },
      { name: "Arm-Fall-Off-Boy (sein Arm fällt buchstäblich ab)", weak: true, emoji: "💪" },
      { name: "Squirrel Girl (besiegt Bösewichte mit Eichhörnchen)", weak: true, emoji: "🐿️" },
      { name: "Stone Boy (wird zu Stein - kann sich dann nicht mehr bewegen)", weak: true, emoji: "🗿" },
      { name: "Doorman (kann sich in eine Tür verwandeln)", weak: true, emoji: "🚪" },
      { name: "Paste-Pot Pete (Bösewicht mit einem Klebe-Topf)", weak: true, emoji: "🪣" },
      { name: "Condiment King (schießt mit Ketchup und Senf)", weak: true, emoji: "🍯" },
      { name: "Kite Man (\"Hell yeah!\")", weak: true, emoji: "🪁" },
      { name: "Bouncing Boy (verwandelt sich in einen Gummiball)", weak: true, emoji: "⚽" },
      { name: "Bat-Mite (kleiner nerviger Fan von Batman)", weak: true, emoji: "🧚" },
    ],
  },
  {
    id: "serien",
    label: "Serien-Charaktere",
    emoji: "📺",
    items: [
      { name: "Walter White" },
      { name: "Tony Soprano" },
      { name: "Eleven" },
      { name: "Michael Scott" },
      { name: "Sheldon Cooper" },
      { name: "Daenerys Targaryen" },
      { name: "Jon Snow" },
      { name: "Tyrion Lannister" },
      { name: "Rick Grimes" },
      { name: "Ted Lasso" },
      { name: "Homer Simpson" },
      { name: "Peter Griffin" },
      { name: "Villanelle" },
      { name: "Saul Goodman" },
      { name: "Dexter Morgan" },
      { name: "Carrie Bradshaw" },
      { name: "Ross Geller" },
      { name: "Michael Scofield" },
      { name: "Barney Stinson" },
      { name: "Don Draper" },
      { name: "Jesse Pinkman" },
      { name: "Arya Stark" },
      { name: "Cersei Lannister" },
      { name: "Rachel Green" },
      { name: "Monica Geller" },
      { name: "Joey Tribbiani" },
      { name: "Chandler Bing" },
      { name: "Phoebe Buffay" },
      { name: "Leslie Knope" },
      { name: "Ron Swanson" },
      { name: "Jack Bauer" },
      { name: "Fox Mulder" },
      { name: "Dana Scully" },
      { name: "Omar Little" },
      { name: "Stringer Bell" },
      { name: "Nucky Thompson" },
      { name: "Frank Underwood" },
      { name: "Claire Underwood" },
      { name: "Sherlock Holmes" },
      { name: "Dwight Schrute" },
      { name: "Der Statist, der in Minute 3 stirbt", weak: true, emoji: "💀" },
      { name: "Der Nachbar, den man nie ganz sieht", weak: true, emoji: "🚪" },
      { name: "Der Praktikant ohne Namen", weak: true, emoji: "📎" },
      { name: "Der Bösewicht, der im Pilotfilm schon stirbt", weak: true, emoji: "🔪" },
      { name: "Kenny (stirbt jede Folge aufs Neue)", weak: true, emoji: "🧥" },
      { name: "Mr. Meeseeks (existiert nur ganz kurz)", weak: true, emoji: "🔵" },
      { name: "Baldrick (treuer, aber planloser Diener)", weak: true, emoji: "🥔" },
      { name: "Kenneth Parcell (der naive Page)", weak: true, emoji: "📺" },
      { name: "Creed Bratton (niemand weiß, was er eigentlich macht)", weak: true, emoji: "😶" },
      { name: "Zapp Brannigan (inkompetenter Raumschiff-Captain)", weak: true, emoji: "🚀" },
    ],
  },
  {
    id: "snacks",
    label: "Snacks",
    emoji: "🍬",
    items: [
      { name: "Haribo Goldbären", emoji: "🐻" },
      { name: "Kinder-Schokolade", emoji: "🍫" },
      { name: "Snickers", emoji: "🍫" },
      { name: "Twix", emoji: "🍫" },
      { name: "Mars", emoji: "🍫" },
      { name: "Milka", emoji: "🍫" },
      { name: "Ferrero Rocher", emoji: "🍫" },
      { name: "Skittles", emoji: "🌈" },
      { name: "M&M's", emoji: "🍬" },
      { name: "Gummibärchen", emoji: "🐻" },
      { name: "Paprika-Chips", emoji: "🥔" },
      { name: "Erdnussflips", emoji: "🥜" },
      { name: "Popcorn", emoji: "🍿" },
      { name: "Lakritz", emoji: "⚫" },
      { name: "Studentenfutter", emoji: "🥜" },
      { name: "Schokokekse", emoji: "🍪" },
      { name: "Salzstangen", emoji: "🥖" },
      { name: "Brezel", emoji: "🥨" },
      { name: "Karamellbonbons", emoji: "🍬" },
      { name: "Toblerone", emoji: "🍫" },
      { name: "Duplo", emoji: "🍫" },
      { name: "Bounty", emoji: "🥥" },
      { name: "Raffaello", emoji: "🥥" },
      { name: "Nutella (löffelweise)", emoji: "🍫" },
      { name: "Oreo", emoji: "🍪" },
      { name: "KitKat", emoji: "🍫" },
      { name: "Lion", emoji: "🍫" },
      { name: "Ritter Sport", emoji: "🍫" },
      { name: "Mon Chéri", emoji: "🍒" },
      { name: "Nimm2", emoji: "🍬" },
      { name: "Werther's Echte", emoji: "🍬" },
      { name: "Chupa Chups", emoji: "🍭" },
      { name: "Cola-Fläschchen (Fruchtgummi)", emoji: "🥤" },
      { name: "Marshmallows", emoji: "🍡" },
      { name: "Käse-Chips", emoji: "🧀" },
      { name: "Tortilla-Chips", emoji: "🌽" },
      { name: "Cashewkerne", emoji: "🥜" },
      { name: "Trockenobst-Mix", emoji: "🍇" },
      { name: "Prinzenrolle", emoji: "🍪" },
      { name: "Toffifee", emoji: "🍬" },
      { name: "Die angebrochene Chipstüte vom letzten Filmabend", weak: true, emoji: "🗑️" },
      { name: "Rosinen", weak: true, emoji: "🍇" },
      { name: "Salzlakritz (Salmiak)", weak: true, emoji: "⚫" },
      { name: "Kichererbsen-Chips", weak: true, emoji: "🫘" },
      { name: "Reiswaffeln", weak: true, emoji: "⚪" },
      { name: "Ungesalzene Mandeln", weak: true, emoji: "🌰" },
      { name: "Zuckerfreie Kaugummis", weak: true, emoji: "🍬" },
      { name: "Diät-Traubenzucker", weak: true, emoji: "🍬" },
      { name: "Vollkorn-Salzstangen", weak: true, emoji: "🥖" },
      { name: "Der letzte Bonbon aus der Weihnachtsschale", weak: true, emoji: "🎄" },
    ],
  },
  {
    id: "fastfood",
    label: "Fast Food",
    emoji: "🍔",
    items: [
      { name: "Pizza", emoji: "🍕" },
      { name: "Burger", emoji: "🍔" },
      { name: "Döner", emoji: "🥙" },
      { name: "Pommes", emoji: "🍟" },
      { name: "Chicken Nuggets", emoji: "🍗" },
      { name: "Currywurst", emoji: "🌭" },
      { name: "Sushi", emoji: "🍣" },
      { name: "Nachos", emoji: "🧀" },
      { name: "Hot Dog", emoji: "🌭" },
      { name: "Tacos", emoji: "🌮" },
      { name: "Kebab", emoji: "🥙" },
      { name: "Falafel", emoji: "🧆" },
      { name: "Pizzabrötchen", emoji: "🍕" },
      { name: "Chicken Wings", emoji: "🍗" },
      { name: "Bratwurst", emoji: "🌭" },
      { name: "Fischbrötchen", emoji: "🐟" },
      { name: "Wrap", emoji: "🌯" },
      { name: "Burrito", emoji: "🌯" },
      { name: "Quesadilla", emoji: "🫓" },
      { name: "Zwiebelringe", emoji: "🧅" },
      { name: "Cheeseburger", emoji: "🍔" },
      { name: "Chicken Sandwich", emoji: "🥪" },
      { name: "Gyros", emoji: "🥙" },
      { name: "Lahmacun", emoji: "🫓" },
      { name: "Pita-Tasche", emoji: "🥙" },
      { name: "Frikadelle", emoji: "🍖" },
      { name: "Langos", emoji: "🫓" },
      { name: "Poutine", emoji: "🍟" },
      { name: "Fish and Chips", emoji: "🐟" },
      { name: "Chili Cheese Fries", emoji: "🌶️" },
      { name: "Loaded Fries", emoji: "🍟" },
      { name: "Empanadas", emoji: "🥟" },
      { name: "Bao Bun", emoji: "🥟" },
      { name: "Instant-Ramen to go", emoji: "🍜" },
      { name: "Gebackener Camembert", emoji: "🧀" },
      { name: "Flammkuchen", emoji: "🫓" },
      { name: "Croque Monsieur", emoji: "🥪" },
      { name: "Hähnchen-Döner", emoji: "🥙" },
      { name: "Falafel-Wrap", emoji: "🌯" },
      { name: "Baked Potato mit Chili", emoji: "🥔" },
      { name: "Die labbrige Tiefkühlpizza vom Kiosk", weak: true, emoji: "🥶" },
      { name: "Der matschige Pommes-Rest von gestern", weak: true, emoji: "🍟" },
      { name: "Der komische vegane Chicken-Nugget-Ersatz", weak: true, emoji: "🥦" },
      { name: "Die labbrige Tankstellen-Currywurst", weak: true, emoji: "⛽" },
      { name: "Der ausgetrocknete Wrap vom Bahnhof", weak: true, emoji: "🚉" },
      { name: "Die überzuckerte Fertigsauce dazu", weak: true, emoji: "🥫" },
      { name: "Der kalte Burger von der Feier", weak: true, emoji: "🥶" },
      { name: "Die zerdrückte Käsestulle aus dem Rucksack", weak: true, emoji: "🎒" },
      { name: "Der 0-Kalorien-Ketchup-Ersatz", weak: true, emoji: "🍅" },
      { name: "Die labbrige Pflicht-Salatbeilage", weak: true, emoji: "🥬" },
    ],
  },
  {
    id: "getraenke",
    label: "Getränke",
    emoji: "🥤",
    items: [
      { name: "Cola", emoji: "🥤" },
      { name: "Fanta", emoji: "🧡" },
      { name: "Sprite", emoji: "🥤" },
      { name: "Red Bull", emoji: "⚡" },
      { name: "Kaffee", emoji: "☕" },
      { name: "Bier", emoji: "🍺" },
      { name: "Eistee", emoji: "🧊" },
      { name: "Mate", emoji: "🧉" },
      { name: "Limonade", emoji: "🍋" },
      { name: "Sprudelwasser", emoji: "💧" },
      { name: "Apfelschorle", emoji: "🍏" },
      { name: "Milchshake", emoji: "🥤" },
      { name: "Smoothie", emoji: "🥤" },
      { name: "Energy-Drink", emoji: "⚡" },
      { name: "Kakao", emoji: "☕" },
      { name: "Orangensaft", emoji: "🍊" },
      { name: "Radler", emoji: "🍺" },
      { name: "Cocktail", emoji: "🍹" },
      { name: "Tee", emoji: "🍵" },
      { name: "Buttermilch", emoji: "🥛" },
      { name: "Stilles Wasser", emoji: "💧" },
      { name: "Traubensaft", emoji: "🍇" },
      { name: "Multivitaminsaft", emoji: "🍹" },
      { name: "Kirschsaft", emoji: "🍒" },
      { name: "Ginger Ale", emoji: "🫚" },
      { name: "Tonic Water", emoji: "🥂" },
      { name: "Eiskaffee", emoji: "☕" },
      { name: "Chai Latte", emoji: "☕" },
      { name: "Matcha Latte", emoji: "🍵" },
      { name: "Kombucha", emoji: "🫙" },
      { name: "Malzbier", emoji: "🍺" },
      { name: "Weinschorle", emoji: "🍷" },
      { name: "Sekt", emoji: "🥂" },
      { name: "Prosecco", emoji: "🥂" },
      { name: "Whiskey-Cola", emoji: "🥃" },
      { name: "Gin Tonic", emoji: "🍸" },
      { name: "Bananenmilch", emoji: "🍌" },
      { name: "Kokoswasser", emoji: "🥥" },
      { name: "Zitronenlimonade", emoji: "🍋" },
      { name: "Holunderblütensaft", emoji: "🌼" },
      { name: "Leitungswasser pur", weak: true, emoji: "🚰" },
      { name: "Schaler Rest-Sekt vom Vortag", weak: true, emoji: "🥂" },
      { name: "Alkoholfreies Bier", weak: true, emoji: "🍺" },
      { name: "Fertig-Eistee aus dem Automaten", weak: true, emoji: "🧃" },
      { name: "Diät-Cola", weak: true, emoji: "🥤" },
      { name: "Kalt gewordener Kaffee", weak: true, emoji: "☕" },
      { name: "Labbrige Apfelschorle aus dem Tetrapak", weak: true, emoji: "🧃" },
      { name: "Extra bitterer Kräutertee, den keiner mag", weak: true, emoji: "🍵" },
      { name: "Der letzte Schluck warme Limo im Glas", weak: true, emoji: "🥤" },
      { name: "Wasser mit komischem Eigengeschmack", weak: true, emoji: "🚰" },
    ],
  },
  {
    id: "autos",
    label: "Autos",
    emoji: "🚗",
    items: [
      { name: "Ferrari", emoji: "🏎️" },
      { name: "Porsche 911", emoji: "🏎️" },
      { name: "Lamborghini", emoji: "🏎️" },
      { name: "Bugatti", emoji: "🏎️" },
      { name: "BMW M3", emoji: "🚗" },
      { name: "Mercedes G-Klasse", emoji: "🚙" },
      { name: "Audi R8", emoji: "🏎️" },
      { name: "Tesla Model S", emoji: "🔋" },
      { name: "McLaren", emoji: "🏎️" },
      { name: "Aston Martin DB11", emoji: "🏎️" },
      { name: "Rolls-Royce", emoji: "🚗" },
      { name: "Bentley", emoji: "🚗" },
      { name: "Koenigsegg", emoji: "🏎️" },
      { name: "Pagani", emoji: "🏎️" },
      { name: "Maserati", emoji: "🏎️" },
      { name: "Ford Mustang", emoji: "🐎" },
      { name: "Dodge Charger", emoji: "🚗" },
      { name: "Range Rover", emoji: "🚙" },
      { name: "Lexus LFA", emoji: "🏎️" },
      { name: "Nissan GT-R", emoji: "🏎️" },
      { name: "Chevrolet Corvette", emoji: "🏎️" },
      { name: "Jaguar F-Type", emoji: "🏎️" },
      { name: "Mercedes-AMG GT", emoji: "🏎️" },
      { name: "BMW i8", emoji: "🔋" },
      { name: "Porsche Taycan", emoji: "🔋" },
      { name: "Audi RS6", emoji: "🚗" },
      { name: "VW Golf GTI", emoji: "🚗" },
      { name: "Mini Cooper S", emoji: "🚗" },
      { name: "Alfa Romeo Giulia", emoji: "🚗" },
      { name: "Fiat 500 Abarth", emoji: "🚗" },
      { name: "Toyota Supra", emoji: "🏎️" },
      { name: "Subaru WRX STI", emoji: "🚗" },
      { name: "Mitsubishi Lancer Evo", emoji: "🚗" },
      { name: "Land Rover Defender", emoji: "🚙" },
      { name: "Jeep Wrangler", emoji: "🚙" },
      { name: "Cadillac Escalade", emoji: "🚙" },
      { name: "Rimac Nevera", emoji: "🔋" },
      { name: "Pininfarina Battista", emoji: "🔋" },
      { name: "Aston Martin DB5", emoji: "🏎️" },
      { name: "Lotus Elise", emoji: "🏎️" },
      { name: "Trabant 601 (Kult-Ostauto, legendär untermotorisiert)", weak: true, emoji: "🐌" },
      { name: "Der Fiat Panda von der Oma", weak: true, emoji: "👵" },
      { name: "Opel Corsa", weak: true, emoji: "🚗" },
      { name: "Dacia Sandero", weak: true, emoji: "🚗" },
      { name: "VW Käfer (Kult, aber lahm)", weak: true, emoji: "🚗" },
      { name: "Renault Twingo", weak: true, emoji: "🚗" },
      { name: "Citroën C1", weak: true, emoji: "🚗" },
      { name: "Lada Niva", weak: true, emoji: "🚙" },
      { name: "Suzuki Alto", weak: true, emoji: "🚗" },
      { name: "Der Firmenwagen-Kombi ohne Extras", weak: true, emoji: "🚘" },
    ],
  },
];

export function categoryById(id: string): Category | undefined {
  return CATEGORIES.find((category) => category.id === id);
}

/** Das Emoji einer Karte: eigenes Emoji, sonst das der Kategorie. */
export function itemEmoji(categoryId: string, item: CategoryItem): string {
  return item.emoji ?? categoryById(categoryId)?.emoji ?? "🃏";
}
