// Alle Kategorien und ihre Karten-Pools.
//
// Jede Kategorie hat 40 Karten. Die meisten sind starke/beliebte
// Einträge, dazu kommen ein paar (meist 3-5) echte, aber im
// Vergleich schwächere oder unbeliebtere Einträge (weak: true) -
// keine erfundenen Spass-Sprüche, sondern Dinge, die es wirklich
// gibt. Pro Runde werden aus den 40 per Zufall 8 gezogen und
// versteigert (siehe engine.ts) - dadurch ist nie im Voraus klar, ob
// eine "weak"-Karte mit dabei ist.
//
// WICHTIG: Die Reihenfolge der Karten in jeder Liste ist absichtlich
// nach Bekanntheit/Stärke sortiert (der stärkste/bekannteste Eintrag
// zuerst, die "weak"-Karten ganz am Ende) - diese Reihenfolge wird
// von der Computer-Einschätzung am Rundenende als versteckte
// Rangliste benutzt (siehe hiddenRank in engine.ts). Wer die Liste
// später ändert oder neue Einträge einfügt, sollte sie deshalb an
// der richtigen Stelle einsortieren statt einfach hinten anzuhängen.
//
// Bilder: standardmäßig Emojis statt echter Fotos/Logos - Fotos von
// echten Promis/Sportlern oder echte Marken-Logos fest einzubauen
// ist urheber-/markenrechtlich heikel, vor allem weil das Spiel
// öffentlich online läuft. Die Namen selbst (Text) zu verwenden ist
// unproblematisch - nur echte Bild-/Logo-Dateien würden ein Risiko
// sein. Wer trotzdem ein echtes Bild will, trägt bei einer Karte
// `image` ein (eine Bild-URL) - das überschreibt dann das Emoji.
// Schlägt das Laden fehl (Link kaputt, Seite offline), springt die
// Anzeige automatisch zurück aufs Emoji.

export type CategoryItem = {
  name: string;
  /** Bekannt, aber im Vergleich schwächer/unbeliebter - zählt beim
   *  Computer-Urteil am Ende weniger. */
  weak?: boolean;
  /** Versteckte Stärke-Einstufung von 0 (schwächste) bis 100
   *  (stärkste), die den Spielern NIE angezeigt wird - nur die
   *  Computer-Einschätzung am Ende rechnet damit (siehe
   *  auctioneerVerdict in engine.ts). Ist bei einer Karte kein
   *  eigener Wert hinterlegt, wird automatisch aus ihrer Position in
   *  der Liste abgeleitet. */
  rank?: number;
  /** Überschreibt das Kategorie-Emoji für diese eine Karte. */
  emoji?: string;
  /** Optional: URL zu einem echten Bild, überschreibt das Emoji. */
  image?: string;
};

export type Category = {
  id: string;
  label: string;
  /** Fällt zurück, wenn eine Karte kein eigenes Emoji hat. */
  emoji: string;
  items: CategoryItem[];
};

export const CATEGORIES: Category[] = [
  {
    id: "fussballspieler",
    label: "Fußball-Spieler",
    emoji: "⚽",
    items: [
      { name: "Lionel Messi" },
      { name: "Cristiano Ronaldo" },
      { name: "Pelé" },
      { name: "Diego Maradona" },
      { name: "Zinédine Zidane" },
      { name: "Ronaldinho" },
      { name: "Johan Cruyff" },
      { name: "Kylian Mbappé" },
      { name: "Erling Haaland" },
      { name: "Neymar" },
      { name: "Franz Beckenbauer" },
      { name: "Ronaldo Nazário" },
      { name: "Andrés Iniesta" },
      { name: "Xavi Hernández" },
      { name: "Kevin De Bruyne" },
      { name: "Robert Lewandowski" },
      { name: "Luka Modrić" },
      { name: "Mohamed Salah" },
      { name: "Thierry Henry" },
      { name: "David Beckham" },
      { name: "Wayne Rooney" },
      { name: "Andrea Pirlo" },
      { name: "Paolo Maldini" },
      { name: "Roberto Baggio" },
      { name: "George Best" },
      { name: "Michael Ballack" },
      { name: "Miroslav Klose" },
      { name: "Philipp Lahm" },
      { name: "Manuel Neuer" },
      { name: "Toni Kroos" },
      { name: "Sergio Ramos" },
      { name: "Gerd Müller" },
      { name: "Lothar Matthäus" },
      { name: "Jude Bellingham" },
      { name: "Vinícius Júnior" },
      { name: "Harry Kane" },
      { name: "Karim Benzema" },
      { name: "Timo Werner", weak: true },
      { name: "Mario Götze", weak: true },
      { name: "André Schürrle", weak: true },
    ],
  },
  {
    id: "fussballvereine",
    label: "Fußballvereine",
    emoji: "🏟️",
    items: [
      { name: "Real Madrid" },
      { name: "FC Barcelona" },
      { name: "Manchester City" },
      { name: "Liverpool" },
      { name: "Manchester United" },
      { name: "Bayern München" },
      { name: "Borussia Dortmund" },
      { name: "Arsenal" },
      { name: "Chelsea" },
      { name: "Paris Saint-Germain" },
      { name: "Inter Mailand" },
      { name: "AC Milan" },
      { name: "Juventus" },
      { name: "Atlético Madrid" },
      { name: "Tottenham Hotspur" },
      { name: "Bayer Leverkusen" },
      { name: "RB Leipzig" },
      { name: "Napoli" },
      { name: "AS Rom" },
      { name: "Benfica Lissabon" },
      { name: "FC Porto" },
      { name: "Ajax Amsterdam" },
      { name: "PSV Eindhoven" },
      { name: "Feyenoord" },
      { name: "Galatasaray" },
      { name: "Fenerbahçe" },
      { name: "Sporting Lissabon" },
      { name: "Sevilla" },
      { name: "Valencia", weak: true },
      { name: "Aston Villa" },
      { name: "Newcastle United" },
      { name: "West Ham United", weak: true },
      { name: "Eintracht Frankfurt" },
      { name: "Borussia Mönchengladbach" },
      { name: "VfB Stuttgart" },
      { name: "Schalke 04", weak: true },
      { name: "Celtic" },
      { name: "Rangers" },
      { name: "Nottingham Forest", weak: true },
      { name: "FC Köln", weak: true },
    ],
  },
  {
    id: "nba",
    label: "NBA-Spieler",
    emoji: "🏀",
    items: [
      { name: "Michael Jordan" },
      { name: "LeBron James" },
      { name: "Kobe Bryant" },
      { name: "Stephen Curry" },
      { name: "Shaquille O'Neal" },
      { name: "Magic Johnson" },
      { name: "Larry Bird" },
      { name: "Kareem Abdul-Jabbar" },
      { name: "Tim Duncan" },
      { name: "Kevin Durant" },
      { name: "Giannis Antetokounmpo" },
      { name: "Nikola Jokić" },
      { name: "Luka Dončić" },
      { name: "Allen Iverson" },
      { name: "Dwyane Wade" },
      { name: "Kevin Garnett" },
      { name: "Dirk Nowitzki" },
      { name: "Hakeem Olajuwon" },
      { name: "Wilt Chamberlain" },
      { name: "Bill Russell" },
      { name: "Kawhi Leonard" },
      { name: "James Harden" },
      { name: "Russell Westbrook", weak: true },
      { name: "Chris Paul" },
      { name: "Anthony Davis" },
      { name: "Jayson Tatum" },
      { name: "Anthony Edwards" },
      { name: "Devin Booker" },
      { name: "Damian Lillard" },
      { name: "Kyrie Irving" },
      { name: "Joel Embiid" },
      { name: "Ja Morant" },
      { name: "Tracy McGrady" },
      { name: "Vince Carter" },
      { name: "Carmelo Anthony" },
      { name: "Paul George" },
      { name: "Dwight Howard", weak: true },
      { name: "Klay Thompson" },
      { name: "DeMar DeRozan" },
      { name: "Ben Simmons", weak: true },
    ],
  },
  {
    id: "reiselaender",
    label: "Länder zum Bereisen",
    emoji: "✈️",
    items: [
      { name: "Japan" },
      { name: "Italien" },
      { name: "USA" },
      { name: "Thailand" },
      { name: "Griechenland" },
      { name: "Spanien" },
      { name: "Frankreich" },
      { name: "Australien" },
      { name: "Neuseeland" },
      { name: "Indonesien (Bali)" },
      { name: "Kanada" },
      { name: "Portugal" },
      { name: "Ägypten" },
      { name: "Marokko" },
      { name: "Südafrika" },
      { name: "Brasilien" },
      { name: "Peru" },
      { name: "Mexiko" },
      { name: "Kroatien" },
      { name: "Island" },
      { name: "Norwegen" },
      { name: "Schweiz" },
      { name: "Vietnam" },
      { name: "Kambodscha" },
      { name: "Vereinigte Arabische Emirate" },
      { name: "Malediven" },
      { name: "Kenia" },
      { name: "Argentinien" },
      { name: "China" },
      { name: "Indien" },
      { name: "Südkorea" },
      { name: "Türkei" },
      { name: "Costa Rica" },
      { name: "Jordanien" },
      { name: "Georgien" },
      { name: "Sri Lanka" },
      { name: "Kolumbien", weak: true },
      { name: "Moldawien", weak: true },
      { name: "Belarus", weak: true },
      { name: "Turkmenistan", weak: true },
    ],
  },
  {
    id: "klamottenmarken",
    label: "Klamotten-Marken",
    emoji: "👕",
    items: [
      { name: "Nike" },
      { name: "Adidas" },
      { name: "Zara" },
      { name: "H&M" },
      { name: "Gucci" },
      { name: "Louis Vuitton" },
      { name: "Chanel" },
      { name: "Levi's" },
      { name: "Puma" },
      { name: "The North Face" },
      { name: "Ralph Lauren" },
      { name: "Tommy Hilfiger" },
      { name: "Calvin Klein" },
      { name: "Vans" },
      { name: "Converse" },
      { name: "New Balance" },
      { name: "Under Armour" },
      { name: "Supreme" },
      { name: "Balenciaga" },
      { name: "Prada" },
      { name: "Versace" },
      { name: "Dior" },
      { name: "Off-White" },
      { name: "Stone Island" },
      { name: "Carhartt" },
      { name: "Patagonia" },
      { name: "Uniqlo" },
      { name: "Bershka" },
      { name: "Pull & Bear" },
      { name: "Jack & Jones" },
      { name: "Hollister" },
      { name: "Abercrombie & Fitch" },
      { name: "American Eagle" },
      { name: "Diesel" },
      { name: "G-Star RAW" },
      { name: "Napapijri" },
      { name: "Ellesse" },
      { name: "C&A", weak: true },
      { name: "Takko Fashion", weak: true },
      { name: "KiK", weak: true },
    ],
  },
  {
    id: "starwars",
    label: "Star-Wars-Figuren",
    emoji: "🚀",
    items: [
      { name: "Darth Vader" },
      { name: "Luke Skywalker" },
      { name: "Yoda" },
      { name: "Han Solo" },
      { name: "Prinzessin Leia" },
      { name: "Obi-Wan Kenobi" },
      { name: "Chewbacca" },
      { name: "R2-D2" },
      { name: "C-3PO" },
      { name: "Palpatine (Darth Sidious)" },
      { name: "Anakin Skywalker" },
      { name: "Boba Fett" },
      { name: "Darth Maul" },
      { name: "Rey" },
      { name: "Kylo Ren" },
      { name: "Finn" },
      { name: "Mace Windu" },
      { name: "Qui-Gon Jinn" },
      { name: "Padmé Amidala" },
      { name: "Lando Calrissian" },
      { name: "General Grievous" },
      { name: "Count Dooku" },
      { name: "Jar Jar Binks" },
      { name: "Ahsoka Tano" },
      { name: "Din Djarin (The Mandalorian)" },
      { name: "Grogu (Baby Yoda)" },
      { name: "Poe Dameron" },
      { name: "BB-8" },
      { name: "Jango Fett" },
      { name: "Mon Mothma" },
      { name: "Admiral Ackbar" },
      { name: "Wedge Antilles" },
      { name: "Bib Fortuna" },
      { name: "Watto" },
      { name: "Jabba the Hutt" },
      { name: "Greedo" },
      { name: "Nien Nunb", weak: true },
      { name: "Dexter Jettster", weak: true },
      { name: "Sio Bibble", weak: true },
      { name: "Wat Tambor", weak: true },
    ],
  },
  {
    id: "deutschemusik",
    label: "Deutsche Musik",
    emoji: "🎤",
    items: [
      { name: "Herbert Grönemeyer" },
      { name: "Rammstein" },
      { name: "Helene Fischer" },
      { name: "Capital Bra" },
      { name: "Sido" },
      { name: "Bushido" },
      { name: "Cro" },
      { name: "Sarah Connor" },
      { name: "Peter Fox" },
      { name: "Nena" },
      { name: "Udo Lindenberg" },
      { name: "Mark Forster" },
      { name: "Apache 207" },
      { name: "RAF Camora" },
      { name: "Kollegah" },
      { name: "Fler" },
      { name: "Kool Savas" },
      { name: "Marteria" },
      { name: "AnnenMayKantereit" },
      { name: "Wincent Weiss" },
      { name: "Max Giesinger" },
      { name: "Namika" },
      { name: "Xavier Naidoo" },
      { name: "Silbermond" },
      { name: "Die Ärzte" },
      { name: "Die Toten Hosen" },
      { name: "Böhse Onkelz" },
      { name: "Juli" },
      { name: "Ich + Ich" },
      { name: "Adel Tawil" },
      { name: "Farid Bang" },
      { name: "Haftbefehl" },
      { name: "Shirin David" },
      { name: "Loredana" },
      { name: "KIZ" },
      { name: "Deichkind" },
      { name: "Clueso" },
      { name: "Prinz Pi", weak: true },
      { name: "Genetikk", weak: true },
      { name: "SDP", weak: true },
    ],
  },
  {
    id: "staedte",
    label: "Städte",
    emoji: "🏙️",
    items: [
      { name: "New York City" },
      { name: "Paris" },
      { name: "London" },
      { name: "Tokio" },
      { name: "Rom" },
      { name: "Berlin" },
      { name: "Barcelona" },
      { name: "Dubai" },
      { name: "Los Angeles" },
      { name: "Sydney" },
      { name: "Amsterdam" },
      { name: "Istanbul" },
      { name: "Hongkong" },
      { name: "Singapur" },
      { name: "Rio de Janeiro" },
      { name: "Kairo" },
      { name: "Moskau" },
      { name: "Peking" },
      { name: "Shanghai" },
      { name: "Venedig" },
      { name: "Wien" },
      { name: "München" },
      { name: "Hamburg" },
      { name: "Prag" },
      { name: "Madrid" },
      { name: "Lissabon" },
      { name: "Kapstadt" },
      { name: "Bangkok" },
      { name: "Seoul" },
      { name: "Toronto" },
      { name: "Chicago" },
      { name: "Miami" },
      { name: "San Francisco" },
      { name: "Athen" },
      { name: "Dublin" },
      { name: "Kopenhagen" },
      { name: "Stockholm" },
      { name: "Bielefeld", weak: true },
      { name: "Duisburg", weak: true },
      { name: "Wuppertal", weak: true },
    ],
  },
  {
    id: "fastfood",
    label: "Fast-Food-Ketten",
    emoji: "🍔",
    items: [
      { name: "McDonald's" },
      { name: "Burger King" },
      { name: "KFC" },
      { name: "Subway" },
      { name: "Domino's Pizza" },
      { name: "Pizza Hut" },
      { name: "Taco Bell" },
      { name: "Starbucks" },
      { name: "Nordsee" },
      { name: "Wendy's" },
      { name: "Five Guys" },
      { name: "Vapiano" },
      { name: "Dunkin'" },
      { name: "Chipotle" },
      { name: "Popeyes" },
      { name: "L'Osteria" },
      { name: "Hans im Glück" },
      { name: "Peter Pane" },
      { name: "Yorma's" },
      { name: "Back-Factory" },
      { name: "Call a Pizza" },
      { name: "Din Döner" },
      { name: "Mr. Wok" },
      { name: "Sushi Circle" },
      { name: "Coa" },
      { name: "Jim Block" },
      { name: "Bagel Brothers" },
      { name: "Freshii" },
      { name: "Shake Shack" },
      { name: "In-N-Out Burger" },
      { name: "IHOP" },
      { name: "Panda Express" },
      { name: "Papa John's" },
      { name: "Little Caesars" },
      { name: "Sonic Drive-In" },
      { name: "Jack in the Box" },
      { name: "A&W", weak: true },
      { name: "Church's Chicken", weak: true },
      { name: "Whataburger", weak: true },
      { name: "Steak 'n Shake", weak: true },
    ],
  },
  {
    id: "essen",
    label: "Essen",
    emoji: "🍽️",
    items: [
      { name: "Pizza" },
      { name: "Pasta" },
      { name: "Sushi" },
      { name: "Burger" },
      { name: "Döner" },
      { name: "Currywurst" },
      { name: "Schnitzel" },
      { name: "Tacos" },
      { name: "Ramen" },
      { name: "Pommes" },
      { name: "Lasagne" },
      { name: "Paella" },
      { name: "Pad Thai" },
      { name: "Curry" },
      { name: "BBQ Ribs" },
      { name: "Steak" },
      { name: "Risotto" },
      { name: "Falafel" },
      { name: "Gyros" },
      { name: "Burrito" },
      { name: "Dim Sum" },
      { name: "Sashimi" },
      { name: "Pho" },
      { name: "Gulasch" },
      { name: "Spätzle" },
      { name: "Kaiserschmarrn" },
      { name: "Fondue" },
      { name: "Raclette" },
      { name: "Tapas" },
      { name: "Bratwurst" },
      { name: "Kebab" },
      { name: "Empanadas" },
      { name: "Croissant" },
      { name: "Waffeln" },
      { name: "Crêpes" },
      { name: "Ceviche" },
      { name: "Labskaus", weak: true },
      { name: "Saure Nieren", weak: true },
      { name: "Haggis", weak: true },
      { name: "Rote Grütze", weak: true },
    ],
  },
  {
    id: "automarken",
    label: "Automarken",
    emoji: "🚘",
    items: [
      { name: "Ferrari" },
      { name: "Lamborghini" },
      { name: "Porsche" },
      { name: "Mercedes-Benz" },
      { name: "BMW" },
      { name: "Audi" },
      { name: "Bugatti" },
      { name: "Rolls-Royce" },
      { name: "Bentley" },
      { name: "Aston Martin" },
      { name: "McLaren" },
      { name: "Toyota" },
      { name: "Volkswagen" },
      { name: "Tesla" },
      { name: "Ford" },
      { name: "Chevrolet" },
      { name: "Honda" },
      { name: "Nissan" },
      { name: "Mazda" },
      { name: "Volvo" },
      { name: "Jaguar" },
      { name: "Land Rover" },
      { name: "Maserati" },
      { name: "Alfa Romeo" },
      { name: "Peugeot" },
      { name: "Renault" },
      { name: "Citroën" },
      { name: "Fiat" },
      { name: "Mini" },
      { name: "Hyundai" },
      { name: "Kia" },
      { name: "Subaru" },
      { name: "Mitsubishi" },
      { name: "Škoda" },
      { name: "Opel" },
      { name: "Seat" },
      { name: "Dacia", weak: true },
      { name: "Lada", weak: true },
      { name: "Proton", weak: true },
      { name: "Trabant", weak: true },
    ],
  },
  {
    id: "videospiele",
    label: "Videospiele",
    emoji: "🎮",
    items: [
      { name: "Minecraft" },
      { name: "GTA V" },
      { name: "GTA San Andreas" },
      { name: "Red Dead Redemption 2" },
      { name: "Fortnite" },
      { name: "Call of Duty: Black Ops II" },
      { name: "Call of Duty: Modern Warfare 2" },
      { name: "FIFA" },
      { name: "Mario Kart Wii" },
      { name: "Super Mario Bros." },
      { name: "Super Mario Odyssey" },
      { name: "The Legend of Zelda: Breath of the Wild" },
      { name: "The Legend of Zelda: Ocarina of Time" },
      { name: "Pokémon Rot/Blau" },
      { name: "Pokémon Diamant/Perl" },
      { name: "Pokémon Schwarz/Weiß" },
      { name: "Wii Sports" },
      { name: "Wii Fit", weak: true },
      { name: "Rocket League" },
      { name: "Roblox" },
      { name: "Terraria" },
      { name: "Among Us" },
      { name: "FIFA Street", weak: true },
      { name: "Need for Speed Most Wanted" },
      { name: "Need for Speed Underground 2" },
      { name: "Gran Turismo" },
      { name: "Forza Horizon 5" },
      { name: "Skyrim" },
      { name: "Fallout 4" },
      { name: "The Witcher 3" },
      { name: "Elden Ring" },
      { name: "Dark Souls" },
      { name: "God of War" },
      { name: "Spider-Man" },
      { name: "The Last of Us" },
      { name: "Uncharted 4" },
      { name: "Super Smash Bros. Ultimate" },
      { name: "Animal Crossing: New Horizons" },
      { name: "Fall Guys" },
      { name: "Goat Simulator", weak: true },
    ],
  },
  {
    id: "erfindungen",
    label: "Erfindungen",
    emoji: "💡",
    items: [
      { name: "Das Rad" },
      { name: "Die Glühbirne" },
      { name: "Das Internet" },
      { name: "Das Telefon" },
      { name: "Der Computer" },
      { name: "Das Smartphone" },
      { name: "Der Buchdruck" },
      { name: "Das Auto" },
      { name: "Das Flugzeug" },
      { name: "Die Dampfmaschine" },
      { name: "Das Penicillin" },
      { name: "Die Impfung" },
      { name: "Das Fahrrad" },
      { name: "Der Fernseher" },
      { name: "Das Radio" },
      { name: "Die Kamera" },
      { name: "Das World Wide Web" },
      { name: "Die Elektrizität (Stromnetz)" },
      { name: "Das GPS" },
      { name: "Die Röntgenstrahlung" },
      { name: "Das Papier" },
      { name: "Die Uhr" },
      { name: "Der Kühlschrank" },
      { name: "Die Waschmaschine" },
      { name: "Der Reißverschluss" },
      { name: "Das Klopapier" },
      { name: "Der Airbag" },
      { name: "Der Laser" },
      { name: "Die Mikrowelle" },
      { name: "Das Bluetooth" },
      { name: "Der USB-Stick" },
      { name: "Die Batterie" },
      { name: "Der Kompass" },
      { name: "Das Teleskop" },
      { name: "Das Mikroskop" },
      { name: "Der 3D-Drucker" },
      { name: "Der Toaster", weak: true },
      { name: "Die Büroklammer", weak: true },
      { name: "Der Post-it-Zettel", weak: true },
      { name: "Der Locher", weak: true },
    ],
  },
  {
    id: "tiere",
    label: "Tiere",
    emoji: "🐾",
    items: [
      { name: "Löwe" },
      { name: "Tiger" },
      { name: "Elefant" },
      { name: "Hund" },
      { name: "Katze" },
      { name: "Pferd" },
      { name: "Delfin" },
      { name: "Wolf" },
      { name: "Bär" },
      { name: "Gorilla" },
      { name: "Panda" },
      { name: "Adler" },
      { name: "Hai" },
      { name: "Giraffe" },
      { name: "Zebra" },
      { name: "Nashorn" },
      { name: "Flusspferd" },
      { name: "Krokodil" },
      { name: "Pinguin" },
      { name: "Koala" },
      { name: "Känguru" },
      { name: "Fuchs" },
      { name: "Eule" },
      { name: "Falke" },
      { name: "Schlange" },
      { name: "Gepard" },
      { name: "Leopard" },
      { name: "Orca" },
      { name: "Wal" },
      { name: "Affe" },
      { name: "Eisbär" },
      { name: "Hase" },
      { name: "Reh" },
      { name: "Igel" },
      { name: "Waschbär" },
      { name: "Papagei" },
      { name: "Nacktmull", weak: true },
      { name: "Molch", weak: true },
      { name: "Assel", weak: true },
      { name: "Regenwurm", weak: true },
    ],
  },
  {
    id: "selbstverteidigung",
    label: "Waffen zur Selbstverteidigung",
    emoji: "🛡️",
    items: [
      { name: "Pfefferspray" },
      { name: "Baseballschläger" },
      { name: "Elektroschocker" },
      { name: "Krav-Maga-Training" },
      { name: "Boxtraining" },
      { name: "Bratpfanne" },
      { name: "Teleskopschlagstock" },
      { name: "Regenschirm" },
      { name: "Taschenalarm" },
      { name: "Nudelholz" },
      { name: "Besenstiel" },
      { name: "Golfschläger" },
      { name: "Hockeyschläger" },
      { name: "Wachhund" },
      { name: "Feuerlöscher" },
      { name: "Taktische Taschenlampe" },
      { name: "Gehstock" },
      { name: "Skateboard" },
      { name: "Kubotan-Schlüsselanhänger" },
      { name: "Schraubenzieher" },
      { name: "Autoschlüssel zwischen den Fingern" },
      { name: "Schwerer Rucksack" },
      { name: "Blumentopf" },
      { name: "Stuhl" },
      { name: "Feuerhaken" },
      { name: "Wanderstock" },
      { name: "Fahrradschloss" },
      { name: "Dickes Buch" },
      { name: "Türkeil-Alarm" },
      { name: "Selbstverteidigungs-App mit Notruf" },
      { name: "Trillerpfeife" },
      { name: "Reizgas-Spray" },
      { name: "Pfefferspray-Gel" },
      { name: "Kettenschloss" },
      { name: "Wanderrucksack mit Hüftgurt" },
      { name: "Selbstverteidigungs-Ring" },
      { name: "Türstopper", weak: true },
      { name: "Wäscheklammer", weak: true },
      { name: "Kissen", weak: true },
      { name: "Sonnenschirm", weak: true },
    ],
  },
  {
    id: "handyapps",
    label: "Handy-Apps",
    emoji: "📱",
    items: [
      { name: "WhatsApp" },
      { name: "Instagram" },
      { name: "TikTok" },
      { name: "YouTube" },
      { name: "Facebook" },
      { name: "Snapchat" },
      { name: "Spotify" },
      { name: "Netflix" },
      { name: "Google Maps" },
      { name: "Gmail" },
      { name: "X (Twitter)" },
      { name: "Telegram" },
      { name: "Amazon" },
      { name: "PayPal" },
      { name: "Uber" },
      { name: "Airbnb" },
      { name: "Discord" },
      { name: "Pinterest" },
      { name: "LinkedIn" },
      { name: "Shazam" },
      { name: "Duolingo" },
      { name: "Zoom" },
      { name: "Signal" },
      { name: "Reddit" },
      { name: "BeReal" },
      { name: "Threads" },
      { name: "Notion" },
      { name: "Google Drive" },
      { name: "Apple Music" },
      { name: "SoundCloud" },
      { name: "Twitch" },
      { name: "Tinder" },
      { name: "Bumble" },
      { name: "Klarna" },
      { name: "Deutsche Bahn App" },
      { name: "Too Good To Go" },
      { name: "Venmo", weak: true },
      { name: "MyFitnessPal", weak: true },
      { name: "CamScanner", weak: true },
      { name: "FlixBus", weak: true },
    ],
  },
];

export function categoryById(id: string): Category | undefined {
  return CATEGORIES.find((category) => category.id === id);
}

/** Das Emoji einer Karte: eigenes Emoji, sonst das der Kategorie. */
export function itemEmoji(categoryId: string, item: CategoryItem): string {
  return item.emoji ?? categoryById(categoryId)?.emoji ?? "🃏";
}
